### ISSUE TITLE
Missing `fromPath` parameter

### ISSUE THREAD

**Issue by artiman16** [RaverJay/CholerAegon#2]
Hello! I did what you say, installed program and pushed it, but I got this error. My command in bash was: nextflow run RaverJay/CholerAegon -r 0.2.0 -profile local --shortreads '/home/artem/CholerAegon/*.fastq' --genome_reference /home/artem/CholerAegon/cholerae_ref.fa --do_all_assemblies --output /home/artem/CholerAegon/results
What's wrong and how can I fix this? Thank you.

**Comment by RaverJay** [comment]
Hi!

What kind of short read data do you have?
I'm afraid that running CholerAegon on only (single-end) shortread data is not working right now, and I didn't get around to fixing the implementation for that.

As a workaround, you can assemble your data yourself (e.g. with Spades) and then run CholerAegon on the assembled genomes.

(FYI the --do_all_assemblies parameter is only intented for hybrid assembly and not needed here)

**Comment by luis-laurindo** [comment]
Please help me, I am trying to run paired end, and I have the same issue: (base) osvaldo@osvaldo-ThinkPad-L13-Yoga-Gen-2:~$ conda activate choleraegon
(choleraegon) osvaldo@osvaldo-ThinkPad-L13-Yoga-Gen-2:~$ nextflow run RaverJay/CholerAegon -r 0.2.0 -profile local,singularity \
--shortreads '/home/osvaldo/Chol*.fastq' --genome_reference /home/osvaldo/Chol/ref.fasta --output /home/osvaldo/Chol/Results
N E X T F L O W  ~  version 23.10.0
Launching `https://github.com/RaverJay/CholerAegon` [confident_bernard] DSL2 - revision: 47a7e4cd22 [0.2.0]
Missing `fromPath` parameter
(choleraegon) osvaldo@osvaldo-ThinkPad-L13-Yoga-Gen-2:~$

**Comment by RaverJay** [comment]
See https://github.com/RaverJay/CholerAegon/issues/4#issuecomment-1808254559

Sorry for the long delay
