### ISSUE TITLE
Missing fromPath Parameter

### ISSUE THREAD

**Issue by luis-laurindo** [RaverJay/CholerAegon#4]
Please help me, I am trying to run paired end: (base) osvaldo@osvaldo-ThinkPad-L13-Yoga-Gen-2:$ conda activate choleraegon
(choleraegon) osvaldo@osvaldo-ThinkPad-L13-Yoga-Gen-2:$ nextflow run RaverJay/CholerAegon -r 0.2.0 -profile local,singularity
--shortreads '/home/osvaldo/Chol*.fastq' --genome_reference /home/osvaldo/Chol/ref.fasta --output /home/osvaldo/Chol/Results
N E X T F L O W ~ version 23.10.0
Launching https://github.com/RaverJay/CholerAegon [confident_bernard] DSL2 - revision: https://github.com/RaverJay/CholerAegon/commit/47a7e4cd2244c2bdb8b8894f4d5e99f6f44cec11 [0.2.0]
Missing fromPath parameter
(choleraegon) osvaldo@osvaldo-ThinkPad-L13-Yoga-Gen-2:~$

**Comment by RaverJay** [comment]
Hi, just released a new version that finally fixes the --shortreads option

Please check the updated README and try again

**Comment by luis-laurindo** [comment]
Thank you so much, it worked just fine.
